combined_macrons_map = {
    '0x1fb0+0x313': 'ἀ',  # ᾰ̓: GREEK SMALL LETTER ALPHA WITH VRACHY COMBINING COMMA ABOVE
    '0x1fb8+0x313': 'Ἀ',  # Ᾰ̓: GREEK CAPITAL LETTER ALPHA WITH VRACHY COMBINING COMMA ABOVE
    '0x1fb0+0x314': 'ἁ',  # ᾰ̔: GREEK SMALL LETTER ALPHA WITH VRACHY COMBINING REVERSED COMMA ABOVE
    '0x1fb8+0x314': 'Ἁ',  # Ᾰ̔: GREEK CAPITAL LETTER ALPHA WITH VRACHY COMBINING REVERSED COMMA ABOVE
    '0x1fb0+0x301': 'ά',  # ᾰ́: GREEK SMALL LETTER ALPHA WITH VRACHY COMBINING ACUTE ACCENT
    '0x1fb0+0x300': 'ὰ',  # ᾰ̀: GREEK SMALL LETTER ALPHA WITH VRACHY COMBINING GRAVE ACCENT
    '0x1fb1+0x313': 'ἀ',  # ᾱ̓: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING COMMA ABOVE
    '0x1fb9+0x313': 'Ἀ',  # Ᾱ̓: GREEK CAPITAL LETTER ALPHA WITH MACRON COMBINING COMMA ABOVE
    '0x1fb1+0x314': 'ἁ',  # ᾱ̔: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING REVERSED COMMA ABOVE
    '0x1fb9+0x314': 'Ἁ',  # Ᾱ̔: GREEK CAPITAL LETTER ALPHA WITH MACRON COMBINING REVERSED COMMA ABOVE
    '0x1fb1+0x301': 'ά',  # ᾱ́: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING ACUTE ACCENT
    '0x1fb1+0x300': 'ὰ',  # ᾱ̀: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING GRAVE ACCENT
    '0x1fb1+0x345': 'α',  # ᾱͅ: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING GREEK YPOGEGRAMMENI

    '0x1fd0+0x313': 'ἰ',  # ῐ̓: GREEK SMALL LETTER IOTA WITH VRACHY COMBINING COMMA ABOVE
    '0x1fd8+0x313': 'Ἰ',  # Ῐ̓: GREEK CAPITAL LETTER IOTA WITH VRACHY COMBINING COMMA ABOVE
    '0x1fd0+0x314': 'ἱ',  # ῐ̔: GREEK SMALL LETTER IOTA WITH VRACHY COMBINING REVERSED COMMA ABOVE
    '0x1fd8+0x314': 'Ἱ',  # Ῐ̔: GREEK CAPITAL LETTER IOTA WITH VRACHY COMBINING REVERSED COMMA ABOVE
    '0x1fd0+0x301': 'ί',  # ῐ́: GREEK SMALL LETTER IOTA WITH VRACHY COMBINING ACUTE ACCENT
    '0x1fd0+0x300': 'ὶ',  # ῐ̀: GREEK SMALL LETTER IOTA WITH VRACHY COMBINING GRAVE ACCENT
    '0x1fd0+0x308': 'ϊ',  # ῐ̈: GREEK SMALL LETTER IOTA WITH VRACHY COMBINING DIAERESIS
    '0x1fd1+0x313': 'ἰ',  # ῑ̓: GREEK SMALL LETTER IOTA WITH MACRON COMBINING COMMA ABOVE
    '0x1fd9+0x313': 'Ἰ',  # Ῑ̓: GREEK CAPITAL LETTER IOTA WITH MACRON COMBINING COMMA ABOVE
    '0x1fd1+0x314': 'ἱ',  # ῑ̔: GREEK SMALL LETTER IOTA WITH MACRON COMBINING REVERSED COMMA ABOVE
    '0x1fd9+0x314': 'Ἱ',  # Ῑ̔: GREEK CAPITAL LETTER IOTA WITH MACRON COMBINING REVERSED COMMA ABOVE
    '0x1fd1+0x301': 'ί',  # ῑ́: GREEK SMALL LETTER IOTA WITH MACRON COMBINING ACUTE ACCENT
    '0x1fd1+0x308': 'ϊ',  # ῑ̈: GREEK SMALL LETTER IOTA WITH MACRON COMBINING DIAERESIS

    '0x1fe0+0x313': 'ὐ',  # ῠ̓: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING COMMA ABOVE
    '0x1fe0+0x314': 'ὑ',  # ῠ̔: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING REVERSED COMMA ABOVE
    '0x1fe8+0x314': 'Ὑ',  # Ῠ̔: GREEK CAPITAL LETTER UPSILON WITH VRACHY COMBINING REVERSED COMMA ABOVE
    '0x1fe0+0x301': 'ύ',  # ῠ́: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING ACUTE ACCENT
    '0x1fe0+0x300': 'ὺ',  # ῠ̀: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING GRAVE ACCENT
    '0x1fe0+0x342': 'ῦ',  # ῠ͂: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING GREEK PERISPOMENI
    '0x1fe0+0x308': 'ϋ',  # ῠ̈: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING DIAERESIS
    '0x1fe0+0x312': 'ύ',  # ῠ̒: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING TURNED COMMA ABOVE
    '0x1fe1+0x314': 'ὑ',  # ῡ̔: GREEK SMALL LETTER UPSILON WITH MACRON COMBINING REVERSED COMMA ABOVE
    '0x1fe9+0x314': 'Ὑ',  # Ῡ̔: GREEK CAPITAL LETTER UPSILON WITH MACRON COMBINING REVERSED COMMA ABOVE
    '0x1fe1+0x301': 'ύ',  # ῡ́: GREEK SMALL LETTER UPSILON WITH MACRON COMBINING ACUTE ACCENT
    '0x1fe1+0x308': 'ϋ',  # ῡ̈: GREEK SMALL LETTER UPSILON WITH MACRON COMBINING DIAERESIS
}
