'''
These are all the vowel length characters used on wiktionary
'''
macron_map = {
    '\u0069\u0306': 'ι',  # ĭ (LATIN SMALL LETTER I WITH BREVE); used for the odd δῐᾰνοιĭ̈́ᾱ

    '\u03B1\u0306': 'α',  # ᾰ (GREEK SMALL LETTER ALPHA WITH VRACHY)
    '\u0391\u0306': 'Α',  # Ᾰ (GREEK CAPITAL LETTER ALPHA WITH VRACHY)
    '\u03B1\u0304': 'α',  # ᾱ (GREEK SMALL LETTER ALPHA WITH MACRON)
    '\u0391\u0304': 'Α',  # Ᾱ (GREEK CAPITAL LETTER ALPHA WITH MACRON)

    '\u03B9\u0306': 'ι',  # ῐ (GREEK SMALL LETTER IOTA WITH VRACHY)
    '\u0399\u0306': 'Ι',  # Ῐ (GREEK CAPITAL LETTER IOTA WITH VRACHY)
    '\u03B9\u0304': 'ι',  # ῑ (GREEK SMALL LETTER IOTA WITH MACRON)
    '\u0399\u0304': 'Ι',  # Ῑ (GREEK CAPITAL LETTER IOTA WITH MACRON)

    '\u03C5\u0306': 'υ',  # ῠ (GREEK SMALL LETTER UPSILON WITH VRACHY)
    '\u03A5\u0306': 'Υ',  # Ῠ (GREEK CAPITAL LETTER UPSILON WITH VRACHY)
    '\u03C5\u0304': 'υ',  # ῡ (GREEK SMALL LETTER UPSILON WITH MACRON)
    '\u03A5\u0304': 'Υ',  # Ῡ (GREEK CAPITAL LETTER UPSILON WITH MACRON)
}
