'''
All the characters with vowel length used on Wiktionary
The 12 letters ᾰᾸᾱᾹῐῘῑῙῠῨῡῩ with macron or vrachy as only diacritic exist in both precomposed and composed versions
'''
macrons_map = {
    '\u1FB0': 'α',  # ᾰ: GREEK SMALL LETTER ALPHA WITH VRACHY
    '\u1FB8': 'Α',  # Ᾰ: GREEK CAPITAL LETTER ALPHA WITH VRACHY
    '\u1FB1': 'α',  # ᾱ: GREEK SMALL LETTER ALPHA WITH MACRON
    '\u1FB9': 'Α',  # Ᾱ: GREEK CAPITAL LETTER ALPHA WITH MACRON
    '\u03B1\u0306': 'α',  # ᾰ: GREEK SMALL LETTER ALPHA WITH VRACHY
    '\u0391\u0306': 'Α',  # Ᾰ: GREEK CAPITAL LETTER ALPHA WITH VRACHY
    '\u03B1\u0304': 'α',  # ᾱ: GREEK SMALL LETTER ALPHA WITH MACRON
    '\u0391\u0304': 'Α',  # Ᾱ: GREEK CAPITAL LETTER ALPHA WITH MACRON
    '\u1FB0\u0313': 'ἀ',  # ᾰ̓: GREEK SMALL LETTER ALPHA WITH VRACHY COMBINING COMMA ABOVE
    '\u1FB8\u0313': 'Ἀ',  # Ᾰ̓: GREEK CAPITAL LETTER ALPHA WITH VRACHY COMBINING COMMA ABOVE
    '\u1FB0\u0314': 'ἁ',  # ᾰ̔: GREEK SMALL LETTER ALPHA WITH VRACHY COMBINING REVERSED COMMA ABOVE
    '\u1FB8\u0314': 'Ἁ',  # Ᾰ̔: GREEK CAPITAL LETTER ALPHA WITH VRACHY COMBINING REVERSED COMMA ABOVE
    '\u1FB0\u0301': 'ά',  # ᾰ́: GREEK SMALL LETTER ALPHA WITH VRACHY COMBINING ACUTE ACCENT
    '\u1FB0\u0300': 'ὰ',  # ᾰ̀: GREEK SMALL LETTER ALPHA WITH VRACHY COMBINING GRAVE ACCENT
    '\u1FB1\u0313': 'ἀ',  # ᾱ̓: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING COMMA ABOVE
    '\u1FB9\u0313': 'Ἀ',  # Ᾱ̓: GREEK CAPITAL LETTER ALPHA WITH MACRON COMBINING COMMA ABOVE
    '\u1FB1\u0314': 'ἁ',  # ᾱ̔: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING REVERSED COMMA ABOVE
    '\u1FB9\u0314': 'Ἁ',  # Ᾱ̔: GREEK CAPITAL LETTER ALPHA WITH MACRON COMBINING REVERSED COMMA ABOVE
    '\u1FB1\u0301': 'ά',  # ᾱ́: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING ACUTE ACCENT
    '\u1FB1\u0300': 'ὰ',  # ᾱ̀: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING GRAVE ACCENT
    '\u1FB1\u0345': 'ᾳ',  # ᾱͅ: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING GREEK YPOGEGRAMMENI

    '\u1FD0': 'ι',  # ῐ: GREEK SMALL LETTER IOTA WITH VRACHY
    '\u1FD8': 'Ι',  # Ῐ: GREEK CAPITAL LETTER IOTA WITH VRACHY
    '\u1FD1': 'ι',  # ῑ: GREEK SMALL LETTER IOTA WITH MACRON
    '\u1FD9': 'Ι',  # Ῑ: GREEK CAPITAL LETTER IOTA WITH MACRON
    '\u03B9\u0306': 'ι',  # ῐ: GREEK SMALL LETTER IOTA WITH VRACHY
    '\u0399\u0306': 'Ι',  # Ῐ: GREEK CAPITAL LETTER IOTA WITH VRACHY
    '\u03B9\u0304': 'ι',  # ῑ: GREEK SMALL LETTER IOTA WITH MACRON
    '\u0399\u0304': 'Ι',  # Ῑ: GREEK CAPITAL LETTER IOTA WITH MACRON
    '\u1FD0\u0313': 'ἰ',  # ῐ̓: GREEK SMALL LETTER IOTA WITH VRACHY COMBINING COMMA ABOVE
    '\u1FD8\u0313': 'Ἰ',  # Ῐ̓: GREEK CAPITAL LETTER IOTA WITH VRACHY COMBINING COMMA ABOVE
    '\u1FD0\u0314': 'ἱ',  # ῐ̔: GREEK SMALL LETTER IOTA WITH VRACHY COMBINING REVERSED COMMA ABOVE
    '\u1FD8\u0314': 'Ἱ',  # Ῐ̔: GREEK CAPITAL LETTER IOTA WITH VRACHY COMBINING REVERSED COMMA ABOVE
    '\u1FD0\u0301': 'ί',  # ῐ́: GREEK SMALL LETTER IOTA WITH VRACHY COMBINING ACUTE ACCENT
    '\u1FD0\u0300': 'ὶ',  # ῐ̀: GREEK SMALL LETTER IOTA WITH VRACHY COMBINING GRAVE ACCENT
    '\u1FD0\u0308': 'ϊ',  # ῐ̈: GREEK SMALL LETTER IOTA WITH VRACHY COMBINING DIAERESIS
    '\u1FD1\u0313': 'ἰ',  # ῑ̓: GREEK SMALL LETTER IOTA WITH MACRON COMBINING COMMA ABOVE
    '\u1FD9\u0313': 'Ἰ',  # Ῑ̓: GREEK CAPITAL LETTER IOTA WITH MACRON COMBINING COMMA ABOVE
    '\u1FD1\u0314': 'ἱ',  # ῑ̔: GREEK SMALL LETTER IOTA WITH MACRON COMBINING REVERSED COMMA ABOVE
    '\u1FD9\u0314': 'Ἱ',  # Ῑ̔: GREEK CAPITAL LETTER IOTA WITH MACRON COMBINING REVERSED COMMA ABOVE
    '\u1FD1\u0301': 'ί',  # ῑ́: GREEK SMALL LETTER IOTA WITH MACRON COMBINING ACUTE ACCENT
    '\u1FD1\u0308': 'ϊ',  # ῑ̈: GREEK SMALL LETTER IOTA WITH MACRON COMBINING DIAERESIS

    '\u1FE0': 'υ',  # ῠ: GREEK SMALL LETTER UPSILON WITH VRACHY
    '\u1FE8': 'Υ',  # Ῠ: GREEK CAPITAL LETTER UPSILON WITH VRACHY
    '\u1FE1': 'υ',  # ῡ: GREEK SMALL LETTER UPSILON WITH MACRON
    '\u1FE9': 'Υ',  # Ῡ: GREEK CAPITAL LETTER UPSILON WITH MACRON
    '\u03C5\u0306': 'υ',  # ῠ: GREEK SMALL LETTER UPSILON WITH VRACHY
    '\u03A5\u0306': 'Υ',  # Ῠ: GREEK CAPITAL LETTER UPSILON WITH VRACHY
    '\u03C5\u0304': 'υ',  # ῡ: GREEK SMALL LETTER UPSILON WITH MACRON
    '\u03A5\u0304': 'Υ',  # Ῡ: GREEK CAPITAL LETTER UPSILON WITH MACRON
    '\u1FE0\u0313': 'ὐ',  # ῠ̓: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING COMMA ABOVE
    '\u1FE0\u0314': 'ὑ',  # ῠ̔: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING REVERSED COMMA ABOVE
    '\u1FE8\u0314': 'Ὑ',  # Ῠ̔: GREEK CAPITAL LETTER UPSILON WITH VRACHY COMBINING REVERSED COMMA ABOVE
    '\u1FE0\u0301': 'ύ',  # ῠ́: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING ACUTE ACCENT
    '\u1FE0\u0300': 'ὺ',  # ῠ̀: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING GRAVE ACCENT
    '\u1FE0\u0342': 'ῦ',  # ῠ͂: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING GREEK PERISPOMENI
    '\u1FE0\u0308': 'ϋ',  # ῠ̈: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING DIAERESIS
    '\u1FE0\u0312': 'ύ',  # ῠ̒: GREEK SMALL LETTER UPSILON WITH VRACHY COMBINING TURNED COMMA ABOVE
    '\u1FE1\u0314': 'ὑ',  # ῡ̔: GREEK SMALL LETTER UPSILON WITH MACRON COMBINING REVERSED COMMA ABOVE
    '\u1FE9\u0314': 'Ὑ',  # Ῡ̔: GREEK CAPITAL LETTER UPSILON WITH MACRON COMBINING REVERSED COMMA ABOVE
    '\u1FE1\u0301': 'ύ',  # ῡ́: GREEK SMALL LETTER UPSILON WITH MACRON COMBINING ACUTE ACCENT
    '\u1FE1\u0308': 'ϋ',  # ῡ̈: GREEK SMALL LETTER UPSILON WITH MACRON COMBINING DIAERESIS
}
